import type { CatalogSet } from "@/lib/types/catalog";

export const mockSets: CatalogSet[] = [
  {
    id: "75192-1",
    name: "Millennium Falcon",
    year: 2017,
    theme_id: 158,
    theme_name: "Star Wars",
    num_parts: 7541,
    num_minifigs: 8,
    img_url: null,
    set_url: null,
    msrp_usd: 849.99,
    status: "available",
    market_value_new: 949.99,
    market_value_used: null,
    pct_change_7d: null,
    pct_change_30d: 11.8,
    pct_change_90d: null,
    growth_annual_pct: null,
    investment_score: null,
  },
  {
    id: "71043-1",
    name: "Hogwarts Castle",
    year: 2018,
    theme_id: 246,
    theme_name: "Harry Potter",
    num_parts: 6020,
    num_minifigs: 4,
    img_url: null,
    set_url: null,
    msrp_usd: 399.99,
    status: "retired",
    market_value_new: 579.99,
    market_value_used: null,
    pct_change_7d: null,
    pct_change_30d: 45.0,
    pct_change_90d: null,
    growth_annual_pct: null,
    investment_score: null,
  },
  {
    id: "41757-1",
    name: "Botanical Garden",
    year: 2023,
    theme_id: 494,
    theme_name: "Friends",
    num_parts: 1072,
    num_minifigs: 6,
    img_url: null,
    set_url: null,
    msrp_usd: 99.99,
    status: "available",
    market_value_new: 89.99,
    market_value_used: null,
    pct_change_7d: null,
    pct_change_30d: -10.0,
    pct_change_90d: null,
    growth_annual_pct: null,
    investment_score: null,
  },
  {
    id: "10276-1",
    name: "Colosseum",
    year: 2020,
    theme_id: 672,
    theme_name: "Creator Expert",
    num_parts: 9036,
    num_minifigs: 0,
    img_url: null,
    set_url: null,
    msrp_usd: 549.99,
    status: "retired",
    market_value_new: 699.99,
    market_value_used: null,
    pct_change_7d: null,
    pct_change_30d: 27.3,
    pct_change_90d: null,
    growth_annual_pct: null,
    investment_score: null,
  },
  {
    id: "42110-1",
    name: "Land Rover Defender",
    year: 2019,
    theme_id: 1,
    theme_name: "Technic",
    num_parts: 2573,
    num_minifigs: 0,
    img_url: null,
    set_url: null,
    msrp_usd: 199.99,
    status: "retired",
    market_value_new: 319.99,
    market_value_used: null,
    pct_change_7d: null,
    pct_change_30d: 60.0,
    pct_change_90d: null,
    growth_annual_pct: null,
    investment_score: null,
  },
  {
    id: "10284-1",
    name: "Camp Nou - FC Barcelona",
    year: 2021,
    theme_id: 672,
    theme_name: "Creator Expert",
    num_parts: 5509,
    num_minifigs: 1,
    img_url: null,
    set_url: null,
    msrp_usd: 349.99,
    status: "available",
    market_value_new: 429.99,
    market_value_used: null,
    pct_change_7d: null,
    pct_change_30d: 22.9,
    pct_change_90d: null,
    growth_annual_pct: null,
    investment_score: null,
  },
  {
    id: "10333-1",
    name: "The Lord of the Rings: Barad-dur",
    year: 2024,
    theme_id: 563,
    theme_name: "Icons",
    num_parts: 5471,
    num_minifigs: 10,
    img_url: null,
    set_url: null,
    msrp_usd: 459.99,
    status: "available",
    market_value_new: 459.99,
    market_value_used: null,
    pct_change_7d: null,
    pct_change_30d: 0.0,
    pct_change_90d: null,
    growth_annual_pct: null,
    investment_score: null,
  },
  {
    id: "10311-1",
    name: "Orchid",
    year: 2022,
    theme_id: 707,
    theme_name: "Botanical Collection",
    num_parts: 608,
    num_minifigs: 0,
    img_url: null,
    set_url: null,
    msrp_usd: 49.99,
    status: "available",
    market_value_new: 47.99,
    market_value_used: null,
    pct_change_7d: null,
    pct_change_30d: -4.0,
    pct_change_90d: null,
    growth_annual_pct: null,
    investment_score: null,
  },
];
